spring:
  datasource:
    url: jdbc:h2:file:/Users/johs/Documents/IntelliJ/sttgw/.local/db/sttgw;MODE=LEGACY;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  thymeleaf:
    cache: false

sttgw:
  capture:
    enabled: false
    dump-path: /Users/johs/Documents/IntelliJ/sttgw/.local/dump
    dump-enabled: false
  audio:
    base-path: /Users/johs/Documents/IntelliJ/sttgw/.local/audio
    retention-days: 30
  stt:
    google:
      credential-path: /Users/johs/Documents/IntelliJ/sttgw/.local/credentials/google-stt-key.json
      streaming-buffer-ms: 200

logging:
  file:
    path: /Users/johs/Documents/IntelliJ/sttgw/.local/logs
    name: /Users/johs/Documents/IntelliJ/sttgw/.local/logs/sttgw.log
  level:
    root: INFO
    com.oxjohs.sttgw: DEBUG
